[
 { "config": {
    "component": "google",
    "component_root": "src/google",
    "licenses": [ "http://opensource.org/licenses/BSD-3-Clause" ]
 } },

 { "plugin": {
    "name": "proto_library",
    "command": "cd $SRC_DIR; go run proto_library_plugin.go"
 } },

 { "cc_library": {
    "name": "cc_proto",
    "dependencies": [ ":proto_lib", ":protoc" ]
 } },

 { "go_library": {
    "name": "go_proto",
    // TODO(cvanarsdale):
    // For now, this is an empty rule. You should install goprotobuf on your
    // system (see https://code.google.com/p/goprotobuf/).
    "dependencies": [ ":protoc" ]
 } },

 { "java_library": {
    "name": "java_proto",
    "java_sources": [ "java/src/main/java/com/google/protobuf/*.java" ],
    "java_root": "java/src/main/java",
    "dependencies": [ ":generate_java_descriptor_proto" ]
 } },

 { "py_library": {
    "name": "py_proto",
    "py_sources": [ "python/google/protobuf/internal/api_implementation.py",
                    "python/google/protobuf/internal/containers.py",
                    "python/google/protobuf/internal/cpp_message.py",
                    "python/google/protobuf/internal/decoder.py",
                    "python/google/protobuf/internal/encoder.py",
                    "python/google/protobuf/internal/enum_type_wrapper.py",
                    "python/google/protobuf/internal/message_listener.py",
                    "python/google/protobuf/internal/python_message.py",
                    "python/google/protobuf/internal/type_checkers.py",
                    "python/google/protobuf/internal/wire_format.py",
                    "python/google/protobuf/descriptor.py",
                    "$GEN_DIR/python/google/protobuf/descriptor_pb2.py",
                    "$GEN_DIR/python/google/protobuf/compiler/plugin_pb2.py",
                    "python/google/protobuf/message.py",
                    "python/google/protobuf/descriptor_database.py",
                    "python/google/protobuf/descriptor_pool.py",
                    "python/google/protobuf/message_factory.py",
                    "python/google/protobuf/reflection.py",
                    "python/google/protobuf/service.py",
                    "python/google/protobuf/service_reflection.py",
                    "python/google/protobuf/text_format.py"
    ],
    "strict_file_mode": false,
    "dependencies": [ ":generate_py_descriptor_proto" ],
    // drop down to just .gen-pkg/google/protobuf/...
    "py_base_dir": "python"
 } },

 { "cc_library": {
    "name": "proto_lib",
    "cc_headers": [ "config.h",
                    "src/google/protobuf/descriptor.h",
                    "src/google/protobuf/descriptor.pb.h",
                    "src/google/protobuf/descriptor_database.h",
                    "src/google/protobuf/dynamic_message.h",
                    "src/google/protobuf/extension_set.h",
                    "src/google/protobuf/extension_set_heavy.cc",
                    "src/google/protobuf/generated_enum_reflection.h",
                    "src/google/protobuf/generated_message_reflection.h",
                    "src/google/protobuf/generated_message_util.h",
                    "src/google/protobuf/io/coded_stream.h",
                    "src/google/protobuf/io/coded_stream_inl.h",
                    "src/google/protobuf/io/gzip_stream.h",
                    "src/google/protobuf/io/package_info.h",
                    "src/google/protobuf/io/printer.h",
                    "src/google/protobuf/io/tokenizer.h",
                    "src/google/protobuf/io/zero_copy_stream.h",
                    "src/google/protobuf/io/zero_copy_stream_impl.h",
                    "src/google/protobuf/io/zero_copy_stream_impl_lite.h",
                    "src/google/protobuf/message.h",
                    "src/google/protobuf/message_lite.h",
                    "src/google/protobuf/package_info.h",
                    "src/google/protobuf/reflection_ops.h",
                    "src/google/protobuf/repeated_field.h",
                    "src/google/protobuf/service.h",
                    "src/google/protobuf/stubs/atomicops.h",
                    "src/google/protobuf/stubs/atomicops_internals_arm_gcc.h",
                    "src/google/protobuf/stubs/atomicops_internals_arm_qnx.h",
                    "src/google/protobuf/stubs/atomicops_internals_atomicword_compat.h",
                    "src/google/protobuf/stubs/atomicops_internals_macosx.h",
                    "src/google/protobuf/stubs/atomicops_internals_mips_gcc.h",
                    "src/google/protobuf/stubs/atomicops_internals_pnacl.h",
                    "src/google/protobuf/stubs/atomicops_internals_x86_gcc.h",
                    "src/google/protobuf/stubs/atomicops_internals_x86_msvc.h",
                    "src/google/protobuf/stubs/common.h",
                    "src/google/protobuf/stubs/hash.h",
                    "src/google/protobuf/stubs/map-util.h",
                    "src/google/protobuf/stubs/once.h",
                    "src/google/protobuf/stubs/platform_macros.h",
                    "src/google/protobuf/stubs/stl_util.h",
                    "src/google/protobuf/stubs/stringprintf.h",
                    "src/google/protobuf/stubs/strutil.h",
                    "src/google/protobuf/stubs/substitute.h",
                    "src/google/protobuf/stubs/template_util.h",
                    "src/google/protobuf/stubs/type_traits.h",
                    "src/google/protobuf/text_format.h",
                    "src/google/protobuf/unknown_field_set.h",
                    "src/google/protobuf/wire_format.h",
                    "src/google/protobuf/wire_format_lite.h",
                    "src/google/protobuf/wire_format_lite_inl.h"
    ],
    "cc_sources": [ "src/google/protobuf/descriptor.cc",
                    "src/google/protobuf/descriptor.pb.cc",
                    "src/google/protobuf/descriptor_database.cc",
                    "src/google/protobuf/dynamic_message.cc",
                    "src/google/protobuf/extension_set.cc",
                    "src/google/protobuf/extension_set_heavy.cc",
                    "src/google/protobuf/generated_message_reflection.cc",
                    "src/google/protobuf/generated_message_util.cc",
                    "src/google/protobuf/io/coded_stream.cc",
                    "src/google/protobuf/io/gzip_stream.cc",
                    "src/google/protobuf/io/printer.cc",
                    "src/google/protobuf/io/tokenizer.cc",
                    "src/google/protobuf/io/zero_copy_stream.cc",
                    "src/google/protobuf/io/zero_copy_stream_impl.cc",
                    "src/google/protobuf/io/zero_copy_stream_impl_lite.cc",
                    "src/google/protobuf/message.cc",
                    "src/google/protobuf/message_lite.cc",
                    "src/google/protobuf/reflection_ops.cc",
                    "src/google/protobuf/repeated_field.cc",
                    "src/google/protobuf/service.cc",
                    "src/google/protobuf/stubs/atomicops_internals_x86_gcc.cc",
                    "src/google/protobuf/stubs/atomicops_internals_x86_msvc.cc",
                    "src/google/protobuf/stubs/common.cc",
                    "src/google/protobuf/stubs/once.cc",
                    "src/google/protobuf/stubs/stringprintf.cc",
                    "src/google/protobuf/stubs/structurally_valid.cc",
                    "src/google/protobuf/stubs/strutil.cc",
                    "src/google/protobuf/stubs/substitute.cc",
                    "src/google/protobuf/text_format.cc",
                    "src/google/protobuf/unknown_field_set.cc",
                    "src/google/protobuf/wire_format.cc",
                    "src/google/protobuf/wire_format_lite.cc"
    ],
  "cc_compile_args": [ "-Wno-error=unused-function" ],
  "cc_linker_args": ["-lz"]
 } },

 { "gen_sh": {
    "name": "generate_java_descriptor_proto",
    "build_cmd": "mkdir -p $GEN_DIR/java/src/main/java; $OBJ_DIR/protoc --java_out=$GEN_DIR/java/src/main/java -Isrc src/google/protobuf/descriptor.proto",
    "outs": [ "$GEN_DIR/src/main/java/com/google/protobuf/DescriptorProtos.java" ],
    "dependencies": [ ":protoc" ]
 } },

 { "gen_sh": {
    "name": "generate_py_descriptor_proto",
    "build_cmd": "mkdir -p $GEN_DIR/python; $OBJ_DIR/protoc --python_out=$GEN_DIR/python -Isrc src/google/protobuf/descriptor.proto src/google/protobuf/compiler/plugin.proto && touch $GEN_DIR/python/google/protobuf/compiler/__init__.py",
    "outs": [ "$GEN_DIR/python/google/protobuf/descriptor_pb2.py",
              "$GEN_DIR/python/google/protobuf/compiler/plugin_pb2.py",
              "$GEN_DIR/python/google/protobuf/compiler/__init__.py"
     ],
    "dependencies": [ ":protoc" ]
 } },

 { "cc_library": {
    "name": "protoc_lib",
    "cc_headers": [ "src/google/protobuf/compiler/code_generator.h",
                    "src/google/protobuf/compiler/command_line_interface.h",
                    "src/google/protobuf/compiler/cpp/cpp_enum.h",
                    "src/google/protobuf/compiler/cpp/cpp_enum_field.h",
                    "src/google/protobuf/compiler/cpp/cpp_extension.h",
                    "src/google/protobuf/compiler/cpp/cpp_field.h",
                    "src/google/protobuf/compiler/cpp/cpp_file.h",
                    "src/google/protobuf/compiler/cpp/cpp_generator.h",
                    "src/google/protobuf/compiler/cpp/cpp_helpers.cc",
                    "src/google/protobuf/compiler/cpp/cpp_helpers.h",
                    "src/google/protobuf/compiler/cpp/cpp_message.h",
                    "src/google/protobuf/compiler/cpp/cpp_message_field.h",
                    "src/google/protobuf/compiler/cpp/cpp_options.h",
                    "src/google/protobuf/compiler/cpp/cpp_primitive_field.h",
                    "src/google/protobuf/compiler/cpp/cpp_service.h",
                    "src/google/protobuf/compiler/cpp/cpp_string_field.h",
                    "src/google/protobuf/compiler/importer.h",
                    "src/google/protobuf/compiler/java/java_doc_comment.h",
                    "src/google/protobuf/compiler/java/java_enum.h",
                    "src/google/protobuf/compiler/java/java_enum_field.h",
                    "src/google/protobuf/compiler/java/java_extension.h",
                    "src/google/protobuf/compiler/java/java_field.h",
                    "src/google/protobuf/compiler/java/java_file.h",
                    "src/google/protobuf/compiler/java/java_generator.h",
                    "src/google/protobuf/compiler/java/java_helpers.cc",
                    "src/google/protobuf/compiler/java/java_helpers.h",
                    "src/google/protobuf/compiler/java/java_message.h",
                    "src/google/protobuf/compiler/java/java_message_field.h",
                    "src/google/protobuf/compiler/java/java_primitive_field.h",
                    "src/google/protobuf/compiler/java/java_service.h",
                    "src/google/protobuf/compiler/java/java_string_field.h",
                    "src/google/protobuf/compiler/package_info.h",
                    "src/google/protobuf/compiler/parser.h",
                    "src/google/protobuf/compiler/plugin.h",
                    "src/google/protobuf/compiler/plugin.pb.h",
                    "src/google/protobuf/compiler/python",
                    "src/google/protobuf/compiler/python/python_generator.cc",
                    "src/google/protobuf/compiler/python/python_generator.h",
                    "src/google/protobuf/compiler/subprocess.h",
                    "src/google/protobuf/compiler/zip_writer.h"
    ],
    "cc_sources": [ "src/google/protobuf/compiler/code_generator.cc",
                    "src/google/protobuf/compiler/command_line_interface.cc",
                    "src/google/protobuf/compiler/cpp/cpp_enum.cc",
                    "src/google/protobuf/compiler/cpp/cpp_enum_field.cc",
                    "src/google/protobuf/compiler/cpp/cpp_extension.cc",
                    "src/google/protobuf/compiler/cpp/cpp_field.cc",
                    "src/google/protobuf/compiler/cpp/cpp_file.cc",
                    "src/google/protobuf/compiler/cpp/cpp_generator.cc",
                    "src/google/protobuf/compiler/cpp/cpp_helpers.cc",
                    "src/google/protobuf/compiler/cpp/cpp_message.cc",
                    "src/google/protobuf/compiler/cpp/cpp_message_field.cc",
                    "src/google/protobuf/compiler/cpp/cpp_primitive_field.cc",
                    "src/google/protobuf/compiler/cpp/cpp_service.cc",
                    "src/google/protobuf/compiler/cpp/cpp_string_field.cc",
                    "src/google/protobuf/compiler/importer.cc",
                    "src/google/protobuf/compiler/java/java_doc_comment.cc",
                    "src/google/protobuf/compiler/java/java_enum.cc",
                    "src/google/protobuf/compiler/java/java_enum_field.cc",
                    "src/google/protobuf/compiler/java/java_extension.cc",
                    "src/google/protobuf/compiler/java/java_field.cc",
                    "src/google/protobuf/compiler/java/java_file.cc",
                    "src/google/protobuf/compiler/java/java_generator.cc",
                    "src/google/protobuf/compiler/java/java_helpers.cc",
                    "src/google/protobuf/compiler/java/java_message.cc",
                    "src/google/protobuf/compiler/java/java_message_field.cc",
                    "src/google/protobuf/compiler/java/java_primitive_field.cc",
                    "src/google/protobuf/compiler/java/java_service.cc",
                    "src/google/protobuf/compiler/java/java_string_field.cc",
                    "src/google/protobuf/compiler/parser.cc",
                    "src/google/protobuf/compiler/plugin.cc",
                    "src/google/protobuf/compiler/plugin.pb.cc",
                    "src/google/protobuf/compiler/python/python_generator.cc",
                    "src/google/protobuf/compiler/subprocess.cc",
                    "src/google/protobuf/compiler/zip_writer.cc"
    ],
    "dependencies": [ ":proto_lib" ]
 } },

 { "cc_binary": {
    "name": "protoc",
    "cc_sources": [ "src/google/protobuf/compiler/main.cc" ],
    "dependencies": [ ":protoc_lib", ":proto_lib" ]
 } }
]

